image: docker:stable

build:
  stage: build
  before_script: 
    - docker info
    - docker login -u $CI_DEPLOY_USER -p $CI_DEPLOY_PASSWORD $CI_REGISTRY
  script:
    - docker build -t registry.lab.jalameta.co.id/images/php/cli:7.2 7.2/cli/
    - docker push registry.lab.jalameta.co.id/images/php-cli:7.2
    - docker build -t registry.lab.jalameta.co.id/images/php/cli:7.3 7.3/cli/
    - docker push registry.lab.jalameta.co.id/images/php/cli:7.3